spring.application.name=vigigate-backend

server.port=${SERVER_PORT:8080}

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/vigigate_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Jakarta}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Jakarta

spring.jackson.time-zone=Asia/Jakarta

app.time-zone=Asia/Jakarta
app.frontend-url=${APP_FRONTEND_URL:http://localhost:4200}
app.seed-demo-data=${APP_SEED_DEMO_DATA:true}
